# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a877c64845b9e074a232faa3262b717e9f0a7c5ac2d573b5610b35faf2e6d0e42f2e20eb9a30b0f88df38a5dec7319474e49b1490b15a9cfad29774e699761

test:
  secret_key_base: af4c9025ca0f38f61e153c5af9a98606e47245d7450137c9096ac4d760a50d40adf736e8b74a837905ab9087c1847bfb0228e5d72637ecf9d20f22e09a4c1762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
